version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'pwd123'
      MYSQL_ROOT_PASSWORD: 'pwd123'
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
  client:
    image: oven/bun:latest
    volumes:
      - "./client:/app"
    depends_on:
      - server
    working_dir: /app
    ports:
      - 7500:7500
    command: bun run start:dev
  server:
    image: oven/bun:latest
    volumes:
      - "./server:/app"
    depends_on:
      - db
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      SECRET_KEY: 'superSecretKey'
    command: bun run start:dev
  test:
    image: oven/bun:latest
    volumes:
      - "./server:/app"
    depends_on:
      - db
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      SECRET_KEY: 'superSecretKey'
    command: bun test
    