version: '3'
services:
  server:
    image: oven/bun:latest
    volumes:
      - "./server:/app"
    depends_on:
      - db
    working_dir: /app
    ports:
      - '3000:3000'
    command: bun run start:dev
  client:
    image: oven/bun:latest
    volumes:
      - "./client:/app"
    depends_on:
      - server
    working_dir: /app
    command: bun run start:dev
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'pwd123'
      MYSQL_ROOT_PASSWORD: 'pwd123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80