version: '3'
services:
  db_test:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'db_test'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'pwd123'
      MYSQL_ROOT_PASSWORD: 'pwd123'
    volumes:
     - ./db_test:/var/lib/mysql
  pma_test:
    image: phpmyadmin
    depends_on:
      - db_test
    environment:
      PMA_HOST: db_test
    ports:
      - 8080:80
  test:
    image: oven/bun:latest
    volumes:
      - "./server:/app"
    depends_on:
      - db_test
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      SECRET_KEY: 'superSecretKey'
    command: 'bun test university'