env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-tabs: off
  "@typescript-eslint/indent":
    - error
    - tab
  "@typescript-eslint/ban-ts-comment": off
